/*
 * Hero - Shoutcast and Icecast Radio Player With History - v4.1.2
 * Copyright 2017-2020, LambertGroup
 *
 */

 (function(u){function N(a,b,d,f){u(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:b.playlistRecordBgOnColor,"border-bottom-color":b.playlistRecordBottomBorderOnColor,color:b.playlistRecordTextOnColor});a.is_very_first||Q(-1,a,b,d);if(""!=b.radio_stream)var v=b.radio_stream;return v}function W(a){var b=new XMLHttpRequest;b.open("HEAD",a,!1);b.send();console.log(a+"   ----   "+b.status);return 404!=b.status}function X(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,B,e){""!=d.optional_images_path?b.playlist_images_arr[e]=
 a:""!=a&&void 0!=a&&(b.playlist_images_arr[e]=a);0!==(e+1)%3&&e!=b.playlist_arr.length-1||setTimeout(function(){O(b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,B)},1E3)}function ca(a){var b;a=a.split("");a.forEach(function(d,f){b="\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00df\u00d2\u00d3\u00d4\u00d5\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00f0\u00c7\u00e7\u00d0\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00d1\u00f1\u0160\u0161\u0178\u00ff\u00fd\u017d\u017e\u2019".indexOf(d);
 -1!=b&&(a[f]="AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz'"[b])});return a.join("").trim()}function L(a,b){var d=new XMLHttpRequest;d.open(a.method,"https://zet.pluginsandthemes.ro/"+a.url);d.onload=d.onerror=function(){b(a.method+" "+a.url+"\n"+d.status+" "+d.statusText+"\n\n"+(d.responseText||""))};/^POST/i.test(a.method)&&(d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.setRequestHeader("X-Requested-With","XMLHttpRequest"));d.send(a.data)}function S(a,
 b,d,f,v,k,y,p,l,w,m,t,q,x,r,A){""!=a.curTitle&&a.isHistoryGenerated&&a.prevTitle!=a.curTitle&&(""!=a.prevTitle&&(30<=a.gen_total_images&&(a.gen_total_images--,a.playlist_arr.pop(),a.playlist_images_arr.pop()),b.grabLastFmPhoto||b.azuracast_get_image||b.mscp_pro_api_url||(a.prev_song_image=b.noImageAvailable),a.gen_total_images++,a.playlist_arr.unshift(a.prevTitle),a.playlist_images_arr.unshift(a.prev_song_image),O(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A)),a.prevTitle=a.curTitle)}function P(a,b,d,f,v,k,y,
 p,l,w,m,t,q,x,r,A){if(b.showOnlyPlayButton||a.isRadiojar||""!=b.azuracast_api_nowplaying_url)a.isRadiojar&&(L({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/now_playing/?my_rand="+Math.random()},function(e){var n=e.indexOf("{");if(-1!==n){var h=e.length;e=e.substr(n,h);e=JSON.parse(e);a.curTitle=e.artist+" - "+e.title;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();J(a,b,d,k,y,p,l,w,m,t,q)}}),S(a,b,k,d,f,v,x,y,p,l,w,m,t,q,r,A)),""!=b.azuracast_api_nowplaying_url&&
 (L({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(e){var n=e.indexOf("{");if(-1!==n){var h=e.length;e=e.substr(n,h);e=JSON.parse(e);a.curTitle=e.now_playing.song.text;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();b.azuracast_get_image&&(a.azuracast_cur_song_image=b.noImageAvailable,""!=e.now_playing.song.art&&(a.azuracast_cur_song_image=e.now_playing.song.art),a.prev_song_image=a.azuracast_cur_song_image);J(a,b,d,k,y,p,l,w,m,t,q)}}),S(a,b,k,d,f,v,x,
 y,p,l,w,m,t,q,r,A));else{if(""!=b.metadata_file_type||""!=b.azuracast_api_nowplaying_url)if(a.now_playing_found=!0,a.now_playing_current_k=b.metadata_file_type-1,""==a.ip||void 0==a.ip)a.ip=1;!1===a.now_playing_found&&a.now_playing_current_k<a.now_playing_arr_lenght&&a.now_playing_current_k++;var B=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"?my_rand="+Math.random():"");0===a.now_playing_current_k&&(B=
 a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"&my_rand="+Math.random():""));""!=b.url_custom_metdata_file&&(B=b.url_custom_metdata_file);""!=a.ip&&a.now_playing_current_k<a.now_playing_arr_lenght?(L({method:"GET",url:B},function(e){var n="";switch(a.now_playing_current_k){case 0:if(-1!=e.indexOf("<SONGTITLE>")){a.now_playing_found=!0;var h=e.indexOf("<SONGTITLE>")+11;var z=e.indexOf("</SONGTITLE>")-h;n=e.substr(h,
 z);a.curTitle=n;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();J(a,b,d,k,y,p,l,w,m,t,q)}else P(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A);break;case 1:h=e.indexOf("<body>")+6;z=e.length;e=e.substr(h,z);e=e.replace("</body></html>","");n=e.split(",");""!=n[6]&&void 0!=n[6]&&"oracle:0"!=n[6]?(a.now_playing_found=!0,n=n[6],a.curTitle=n,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,k,y,p,l,w,m,t,q)):P(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A);break;case 2:h=e.indexOf('{"icestats":');if(-1!==
 h){z=e.length;e=e.substr(h,z);e=JSON.parse(e);h=!1;var D=0;if(e.icestats.source instanceof Array){for(;D<Object.keys(e.icestats.source).length&&!h;)z=e.icestats.source[D].listenurl,0<z.indexOf(a.mount_point)&&(h=!0,D--),D++;h&&""!=e.icestats.source[D].title&&void 0!=e.icestats.source[D].title&&(a.now_playing_found=!0,n=e.icestats.source[D].title,a.curTitle=n,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,k,y,p,l,w,m,t,q))}else""!=e.icestats.source.title&&void 0!=e.icestats.source.title&&
 (a.now_playing_found=!0,n=e.icestats.source.title,a.curTitle=n,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,k,y,p,l,w,m,t,q))}""==n&&(a.now_playing_found=!1,P(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A));break;case 3:""!=a.mount_point&&(h=e.indexOf(a.mount_point));0<h&&(z=e.length,e=e.substr(h,z));z=e.indexOf("Currently playing:");-1==z&&(z=e.indexOf("Current Song:"));0<z&&(a.now_playing_found=!0,h=e.indexOf('<td class="streamstats">',z),h=0<h?h+24:e.indexOf('<td class="streamdata">',z)+
 23,z=e.indexOf("</td>",h),n=e.substr(h,z-h),a.curTitle=n,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,k,y,p,l,w,m,t,q));""==n&&(a.now_playing_found=!1,P(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A));break;default:a.now_playing_found=!0,a.curTitle="Not available...",a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,k,y,p,l,w,m,t,q)}}),S(a,b,k,d,f,v,x,y,p,l,w,m,t,q,r,A)):(curSong="Data not available...",a.curTitle=curSong,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),
 J(a,b,d,k,y,p,l,w,m,t,q))}}function T(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,B){b.grabLastFmPhoto&&(clearTimeout(a.musicbrainzHistory_setTimeout_arr[B]),a.musicbrainzHistory_setTimeout_arr[B]=setTimeout(function(){var e=a.playlist_arr[B].split("-");e[0]=e[0].trim();a.the_artist_id_history_arr[B]="";a.the_wikidata_id_history_arr[B]="";a.wiki_photo_path=b.noImageAvailable;e[0]=e[0].trim();if(""!=b.optional_images_path)e=b.optional_images_path+a.playlist_arr[B]+".jpg",e=encodeURI(e),e=e.replace("(","%28"),
 e=e.replace(")","%29"),e=e.replace("&apos;","%27"),e=e.replace("&amp;","%26"),W(e)||(e=b.noImageAvailable),X(e,a,b,f,d,q,t,x,v,k,y,p,l,w,m,r,A,B);else{var n=e[0];n=n.toLowerCase();n=ca(n);u.get("https://theaudiodb.com/api/v1/json/"+a.zerx+"/search.php?s="+e[0],{},function(h){var z=b.noImageAvailable;h.artists instanceof Array&&""!=h.artists[0].strArtistThumb&&void 0!=h.artists[0].strArtistThumb&&null!=h.artists[0].strArtistThumb&&(z=h.artists[0].strArtistThumb);X(z,a,b,f,d,q,t,x,v,k,y,p,l,w,m,r,A,
 B)})}},3E3*(B+1)))}function da(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,B){clearInterval(a.radioReaderAjaxInterval);if(-1!==b.radio_stream.indexOf("radiojar.com")){a.isRadiojar=!0;var e=b.radio_stream.match(a.myregexp_radiojar);null!=e&&(a.http_or_https=e[1],a.ip=e[2],a.mount_point=e[3],a.port="")}else-1==b.radio_stream.indexOf("/",9)&&(b.radio_stream+="/;"),"/"==b.radio_stream.charAt(b.radio_stream.length-1)&&(b.radio_stream+=";"),e=b.radio_stream.match(a.myregexp),null!=e&&(a.http_or_https=e[1],a.ip=e[2],
 a.port=e[3],a.mount_point=e[4],";"==a.mount_point.trim()&&(a.mount_point=""));m.css({width:b.playerWidth+"px",height:b.imageHeight+"px",background:"url("+b.noImageAvailable+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});if(!b.showOnlyPlayButton){P(a,b,d,q,t,f,v,k,y,p,l,w,m,x,r,A);a.radioReaderAjaxInterval=setInterval(function(){P(a,b,d,q,t,f,v,k,y,p,l,w,m,x,r,A)},1E3*b.nowPlayingInterval);a.playlist_arr=[];a.playlist_images_arr=[];var n=
 -1,h,z,D,c=0;a.isRadiojar&&L({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/tracks/?my_rand="+Math.random()},function(g){h=g.indexOf("[{");if(-1!==h){z=g.length;g=g.substr(h,z);var E=JSON.parse(g);E.reverse()}for(c=0;c<Object.keys(E).length;c++)""!=E[c].track&&"Empty Title"!=E[c].track&&(n++,a.playlist_arr[n]=E[c].artist+" - "+E[c].track,a.playlist_images_arr[n]=b.noImageAvailable,T(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,n));a.playlist_arr.length?O(a,b,f,d,q,t,x,v,k,y,p,l,w,m,
 r,A):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&B.click()});""!=b.azuracast_api_nowplaying_url&&L({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(g){h=g.indexOf("{");if(-1!==h){z=g.length;g=g.substr(h,z);g=JSON.parse(g);for(c=0;c<Object.keys(g.song_history).length;c++)""!=g.song_history[c].song.text&&"Empty Title"!=g.song_history[c].song.text.text&&(n++,a.playlist_arr[n]=g.song_history[c].song.text,a.playlist_images_arr[n]=b.noImageAvailable,b.azuracast_get_image&&
 ""!=g.song_history[c].song.art&&(a.playlist_images_arr[n]=g.song_history[c].song.art),T(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,n));a.playlist_arr.length?O(a,b,f,d,q,t,x,v,k,y,p,l,w,m,r,A):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&B.click()}});a.isRadiojar||""!=b.azuracast_api_nowplaying_url||b.iceCastFirst||L({method:"GET",url:a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.history_arr[a.history_current_k]},function(g){if(-1!=g.indexOf("Current Song"))for(h=g.indexOf("Current Song")+12,z=g.length,g=
 g.substr(h,z),D=g.split("</td><td>"),D.shift(),g=0;g<D.length;g++)h=D[g].indexOf("</"),-1!=h&&(z=h,D[g]=D[g].substr(0,z),D[g]=D[g].replace(/<\/?[^>]+(>|$)/g,""),""!=D[g]&&"Empty Title"!=D[g]&&(n++,a.playlist_arr[n]=D[g],a.playlist_arr[n]=a.playlist_arr[n].replace(/(\r?\n|\r)/gm," ").trim(),a.playlist_images_arr[n]=b.noImageAvailable,T(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,n)));a.playlist_arr.length?O(a,b,f,d,q,t,x,v,k,y,p,l,w,m,r,A):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&B.click()})}a.isFlashNeeded?
 ""!=a.myFlashObject&&a.myFlashObject.myAS3function(N(a,b,d,f),b.initialVolume):(document.getElementById(a.audioID).src=N(a,b,d,f),document.getElementById(a.audioID).load(),b.autoPlay&&v.click())}function R(a,b,d,f){d.css({background:"url("+f+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});b.prev_song_image=b.cur_song_image;b.cur_song_image=f}function J(a,b,d,f,v,k,y,p,l,w,m){a.curSongText="";b.showTitle&&null!=a.curTitle&&""!=a.curTitle&&
 (a.curSongText+=a.curTitle);b.showRadioStation&&null!=b.radio_name&&""!=b.radio_name&&l.html(b.radio_name);var t=a.curTitle.split("-"),q=b.noImageAvailable;t[0]=t[0].trim();3<=t.length&&(t[0]=t[0].trim()+"-"+t[1].trim());if(b.grabLastFmPhoto&&""!=t[0].trim()){var x="";a.the_artist_id="";a.the_wikidata_id="";q=b.noImageAvailable;a.wiki_photo_path=q;clearTimeout(a.musicbrainz_setTimeout);clearTimeout(a.no_artist_image_setTimeout);t[0]=t[0].trim();""!=t[0]&&void 0!=t[0]&&a.prevTitle!=a.curTitle&&(m.css({background:"url("+
 q+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"}),clearTimeout(a.musicbrainz_setTimeout),a.musicbrainz_setTimeout=setTimeout(function(){""!=b.optional_images_path?(x=b.optional_images_path+a.curTitle+".jpg",x=encodeURI(x),x=x.replace("(","%28"),x=x.replace(")","%29"),x=x.replace("&apos;","%27"),x=x.replace("&amp;","%26"),W(x)||(x=b.noImageAvailable),q=x,R(b,a,m,q)):u.get("https://theaudiodb.com/api/v1/json/"+a.zerx+"/search.php?s="+t[0],{},
 function(r){var A=b.noImageAvailable;r.artists instanceof Array&&""!=r.artists[0].strArtistThumb&&void 0!=r.artists[0].strArtistThumb&&null!=r.artists[0].strArtistThumb&&(A=r.artists[0].strArtistThumb);R(b,a,m,A)})}))}else b.azuracast_get_image&&(q=a.azuracast_cur_song_image,R(b,a,m,q)),""!=b.mscp_pro_api_url&&a.prevTitle!=a.curTitle&&L({method:"GET",url:b.mscp_pro_api_url},function(r){var A=r.indexOf('{"mscp":'),B=r.length;-1!==A&&(r=r.substr(A,B),r=JSON.parse(r),""!=r.mscp.info[0].cover&&-1==r.mscp.info[0].cover.indexOf("nocover.png")&&
 (q=r.mscp.info[0].cover.replace(/(\s)/g,"%20"),q=r.mscp.info[0].cover.replace(/100x100/g,"400x400")),R(b,a,m,q))});a.curSongText&&(d=a.curSongText.split("-"),a.curSongAuthorText=d[0].trim(),2<=d.length&&(a.curSongText=d[1].trim()),3<=d.length&&(a.curSongAuthorText=d[0].trim()+"-"+d[1].trim(),a.curSongText=d[2].trim()),k.html(Y(a.curSongAuthorText,b)),p.css({width:"auto"}),a.isStationTitleInsideScrolling=!1,a.stationTitleInsideWait=0,p.stop(),p.css({"margin-left":0}),p.html(a.curSongText),clearInterval(a.timeupdateInterval),
 p.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&p.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,p.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),p.css({"margin-left":0}),p.stop().animate({"margin-left":b.playerWidth-p.width()+"px"},parseInt(1E4*(p.width()-b.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=
 !1})):!a.isStationTitleInsideScrolling&&p.width()>a.titleWidth&&a.stationTitleInsideWait++},300):p.css({width:"100%"}))}function Q(a,b,d,f){if(b.gen_total_images>d.numberOfThumbsPerScreen){var v=(b.thumbsHolder_ThumbHeight+1)*(b.gen_total_images-d.numberOfThumbsPerScreen),k=0;f.stop(!0,!0);u("html, body").off("touchstart touchmove").on("touchstart touchmove",function(y){y.preventDefault()});-1==a||b.isCarouselScrolling?!b.isCarouselScrolling&&b.gen_total_images>d.numberOfThumbsPerScreen&&(b.isCarouselScrolling=
 !0,k=-1*parseInt((b.thumbsHolder_ThumbHeight+1)*b.current_img_no,10),Math.abs(k)>v&&(k=-1*v),b.gen_total_images>d.numberOfThumbsPerScreen&&d.showPlaylist&&b.audio6_html5_sliderVertical.slider("value",100+parseInt(100*k/v)),f.animate({top:k+"px"},500,"easeOutCubic",function(){b.isCarouselScrolling=!1;u("html, body").off("touchstart touchmove").on("touchstart touchmove",function(y){})})):(b.isCarouselScrolling=!0,k=2>=a?-1*v:parseInt(v*(a-100)/100,10),0<k&&(k=0),f.animate({top:k+"px"},1100,"easeOutQuad",
 function(){b.isCarouselScrolling=!1;u("html, body").off("touchstart touchmove").on("touchstart touchmove",function(y){})}))}}function U(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A,B,e,n,h,z,D,c,g,E,G){f.width(d.playerWidth);if(d.showOnlyPlayButton||b.isMinified)a="none";"none"==a?r.css({width:"0px",height:"0px"}):r.css({width:d.playerWidth+"px",height:parseInt(d.playerWidth/d.origWidth*d.imageHeight,10)+"px"});d.sticky&&d.startMinified?r.css({display:"none",top:"0px",left:"0px"}):r.css({display:a,top:"0px",left:"0px"});
 b.imageTopPos=0;b.imageLeftPos=0;b.frameBehindTextTopPos=r.height();b.frameBehindTextLeftPos=0;d.showOnlyPlayButton?e.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:d.frameBehindTextColor,width:0,height:0}):e.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:d.frameBehindTextColor,height:l.height()+2*b.playVerticalPadding+"px"});b.playTopPos=b.frameBehindTextTopPos+b.playVerticalPadding;b.playLeftPos=b.frameBehindTextLeftPos+b.playHorizontalPadding;
 l.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"});b.titleWidth=d.playerWidth-4*b.playHorizontalPadding-l.width();b.titleTopPos=b.playTopPos+3;b.titleLeftPos=l.width()+2*b.playHorizontalPadding;m.css({color:d.songTitleColor,top:b.titleTopPos+"px",left:b.titleLeftPos+"px",width:b.titleWidth+"px"});b.lineSeparatorTopPos=b.titleTopPos+m.height()+2;b.lineSeparatorLeftPos=b.titleLeftPos;n.css({background:d.lineSeparatorColor,top:b.lineSeparatorTopPos+"px",left:b.lineSeparatorLeftPos+"px",width:b.titleWidth+
 "px"});b.authorTopPos=b.lineSeparatorTopPos+8;b.authorLeftPos=b.titleLeftPos;w.css({color:d.authorTitleColor,top:b.authorTopPos+"px",left:b.authorLeftPos+"px",width:b.titleWidth+"px"});b.minimizeTopPos=b.playTopPos;!d.sticky||d.showOnlyPlayButton?(b.minimizeRightPos=0,z.css({display:"none",padding:0,margin:0})):d.sticky&&(b.minimizeRightPos=b.smallButtonDistance,z.css({top:b.minimizeTopPos+"px",right:b.minimizeRightPos+"px"}));b.frameBehindButtonsTopPos=b.frameBehindTextTopPos+e.height();b.frameBehindButtonsLeftPos=
 0;d.showOnlyPlayButton?h.css({background:d.frameBehindButtonsColor,height:0,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"}):h.css({background:d.frameBehindButtonsColor,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"});b.radioStationTopPos=b.frameBehindButtonsTopPos+Math.floor(h.height()-q.height())/2;b.radioStationLeftPos=b.playHorizontalPadding;q.css({color:d.radioStationColor,top:b.radioStationTopPos+"px",left:b.radioStationLeftPos+"px",width:b.titleWidth+
 "px"});0==b.historyButWidth&&(b.historyButWidth=D.width());b.showhidehistoryTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-D.height())/2);b.temp_showHistoryBut?(b.showhideplaylistRightPos=2*b.smallButtonDistance,D.css({display:"block",width:b.historyButWidth+"px",top:b.showhidehistoryTopPos+"px",right:b.showhideplaylistRightPos+"px"})):(b.showhideplaylistRightPos=0,D.css({display:"none",width:0,padding:0,margin:0}));c.css({display:"none",width:0,padding:0,margin:0});b.volumeTopPos=b.frameBehindButtonsTopPos+
 Math.floor((h.height()-g.height())/2);d.showVolume?(b.volumeRightPos=b.showhideplaylistRightPos+D.width()+b.smallButtonDistance,g.css({top:b.volumeTopPos+"px",right:b.volumeRightPos+"px"})):(b.volumeRightPos=b.showhideplaylistRightPos+D.width(),g.css({display:"none",width:0,padding:0,margin:0}));b.twitterTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-E.height())/2);d.showTwitterBut?(b.twitterRightPos=b.volumeRightPos+g.width()+b.smallButtonDistance,E.css({top:b.twitterTopPos+"px",right:b.twitterRightPos+
 "px"})):(b.twitterRightPos=b.volumeRightPos+g.width(),E.css({display:"none",width:0,padding:0,margin:0}));b.facebookTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-G.height())/2);d.showFacebookBut?(b.facebookRightPos=b.twitterRightPos+E.width()+b.smallButtonDistance,G.css({top:b.facebookTopPos+"px",right:b.facebookRightPos+"px"})):(b.facebookRightPos=b.twitterRightPos,G.css({display:"none",width:0,padding:0,margin:0}))}function O(a,b,d,f,v,k,y,p,l,w,m,t,q,x,r,A){if(!b.showOnlyPlayButton){f.stop(!0,
 !0);a.isCarouselScrolling=!1;u(".readingData",k).css({display:"none"});p=parseInt(b.playerWidth/b.origWidth*b.historyRecordTitleLimit,10);l=parseInt(b.playerWidth/b.origWidth*b.historyRecordAuthorLimit,10);w=[];a.isHistoryGenerated=!0;f.html("");for(m=a.gen_total_images=0;m<a.playlist_arr.length;m++)a.gen_total_images++,w=a.playlist_arr[m].split("-"),1>w.length?a.gen_total_images--:(a.thumbsHolder_Thumb=u('<div class="thumbsHolder_ThumbOFF" rel="'+(a.gen_total_images-1)+'" data-origID="'+m+'"><div class="padding"><div class="img_div" style="background-image:url('+
 a.playlist_images_arr[m]+');background-color:#000000;"></div><span class="titlex">'+Z(w[1],p,b)+'</span><span class="authorx">'+Z(w[0],l,b)+"</span></div></div>"),f.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=a.thumbsHolder_Thumb.height()),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.gen_total_images+"px",background:b.historyRecordBgColor,"border-bottom-color":b.historyRecordBottomBorderColor,color:b.historyRecordTextColor}),u(".titlex",
 a.thumbsHolder_Thumb).css({color:b.historyRecordSongColor,"border-bottom-color":b.historyRecordSongBottomBorderColor}),u(".authorx",a.thumbsHolder_Thumb).css({color:b.historyRecordAuthorColor}),a.current_img_no=0);v.height(2*b.historyPadding+(a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen+A.height()+b.historyPadding);k.height((a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen);k.css({"margin-top":A.height()+b.historyPadding+"px"});y.css({padding:b.historyPadding+"px"});a.thumbsHolder_Thumbs=
 u(".thumbsHolder_ThumbOFF",d);a.wrapperHeight=a.audioPlayerHeight+v.height()+b.historyTopPos;if(!b.showHistory||!b.showHistoryOnInit||0>v.css("margin-top").substring(0,v.css("margin-top").length-2))a.wrapperHeight=a.audioPlayerHeight;a.isMinified||r.css({height:a.wrapperHeight+"px"});a.gen_total_images>b.numberOfThumbsPerScreen&&b.showHistory?(b.isPlaylistSliderInitialized&&a.audio6_html5_sliderVertical.slider("destroy"),a.audio6_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,
 max:100,step:1,value:100,slide:function(B,e){Q(e.value,a,b,f)}}),b.isPlaylistSliderInitialized=!0,a.audio6_html5_sliderVertical.css({display:"inline",position:"absolute",height:v.height()-20-3*b.historyPadding-A.height()+"px",left:d.width()-a.audio6_html5_sliderVertical.width()-b.historyPadding+"px",top:a.audioPlayerHeight+b.historyTopPos+2*b.historyPadding+2+A.height()+"px"}),b.showHistoryOnInit||a.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),u(".thumbsHolder_ThumbOFF",d).css({width:d.width()-
 a.audio6_html5_sliderVertical.width()-2*b.historyPadding-3+"px"})):(b.isPlaylistSliderInitialized&&(a.audio6_html5_sliderVertical.slider("destroy"),b.isPlaylistSliderInitialized=!1),u(".thumbsHolder_ThumbOFF",d).css({width:d.width()-2*b.historyPadding+"px"}));k.mousewheel(function(B,e,n,h){a.gen_total_images>b.numberOfThumbsPerScreen&&(B.preventDefault(),B=a.audio6_html5_sliderVertical.slider("value"),1<parseInt(B)&&-1==parseInt(e)||100>parseInt(B)&&1==parseInt(e))&&(B+=3*e,a.audio6_html5_sliderVertical.slider("value",
 B),Q(B,a,b,f))});f.css({top:"0px"})}}function Y(a,b){b.preserveOriginalUpperLowerCase||(a=a.toLowerCase(),a=a.replace(/\b[a-z]/g,function(d){return d.toUpperCase()}),a=a.replace(/&Apos;/gi,"'"),a=a.replace(/&Amp;/gi,"&"),a=a.replace(/'[A-Z]/g,function(d){return d.toLowerCase()}));return a}function Z(a,b,d){a=String(a);var f="";if(a.length>b){a=a.substring(0,b);var v=a.split(" ");a=a.substring(b-2,b-1);""!=a&&(v.pop(),f="...");a=v.join(" ")}a=Y(a,d);return a+f}function ea(){u("audio").each(function(){u(".AudioPlay").removeClass("AudioPause");
 u(this)[0].pause()})}function aa(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,d=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=d.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,d=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=d.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function fa(a){var b=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&
 ""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||(b=!0);return b}var K=navigator.userAgent.toLowerCase();u.fn.audio6_html5=function(a){a=u.extend({},u.fn.audio6_html5.defaults,a);aa();return this.each(function(){var b=u(this),d=u('<div class="frameBehindText"></div><div class="frameBehindButtons"></div> <div class="ximage"></div> <div class="AudioControls"> <a class="AudioCloseBut" title="Minimize"></a><a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="songAuthorLineSeparator"></div>  <div class="songAuthor"></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="historyPadding">  <div class="historyTitle"></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>'),
 f=b.parent(".audio6_html5");f.addClass(a.skin);f.append(d);var v=u(".frameBehindText",f),k=u(".frameBehindButtons",f);u(".AudioControls",f);var y=u(".AudioFacebook",f),p=u(".AudioTwitter",f),l=u(".AudioPlay",f),w=u(".AudioShowHidePlaylist",f),m=u(".VolumeButton",f),t=u(".VolumeSlider",f),q=u(".AudioCloseBut",f),x=u(".songTitle",f),r=u(".songTitleInside",f),A=u(".songAuthor",f),B=u(".songAuthorLineSeparator",f),e=u(".radioStation",f),n=u(".ximage",f),h=u(".historyTitle",f);f.wrap("<div class='the_wrapper'></div>");
 var z=f.parent(),D=aa();if(-1!=K.indexOf("ipad")||-1!=K.indexOf("iphone")||-1!=K.indexOf("ipod")||-1!=K.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoPlay=!1;f.css({background:"transparent"});d=Math.floor(1E5*Math.random());var c={current_img_no:0,origID:0,is_very_first:!0,total_images:0,gen_total_images:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",playlist_images_arr:"",isCarouselScrolling:!1,isHistoryGenerated:!1,isStationTitleInsideScrolling:!1,curTitle:"",
 prevTitle:"",cur_song_image:"",prev_song_image:"",azuracast_cur_song_image:a.noImageAvailable,curSongText:"",curSongAuthorText:"",stationTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,wrapperHeight:0,temp_showHistoryBut:!0,historyButWidth:0,isRadiojar:!1,historyInitialHeight:90,thumbsHolder_Thumb:u('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",constantDistance:0,titleWidth:0,radioStationTopPos:0,radioStationLeftPos:0,
 titleTopPos:0,titleLeftPos:0,lineSeparatorTopPos:0,lineSeparatorLeftPos:0,authorTopPos:0,authorLeftPos:0,minimizeTopPos:0,minimizeRightPos:0,isMinified:!1,imageTopPos:0,imageLeftPos:0,frameBehindButtonsTopPos:0,frameBehindButtonsLeftPos:0,frameBehindTextTopPos:0,frameBehindTextLeftPos:0,playTopPos:0,playLeftPos:0,volumeTopPos:0,volumeRightPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhidehistoryTopPos:0,showhideplaylistRightPos:0,smallButtonDistance:4,playVerticalPadding:10,playHorizontalPadding:16,
 facebookTopPos:0,facebookRightPos:0,twitterTopPos:0,twitterRightPos:0,origParentFloat:"",origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,myregexp:/^(http|https):\/\/(.*):(.*)\/(.*)$/,myregexp_radiojar:/^(http|https):\/\/(.*)\/(.*)$/,http_or_https:"http",ip:"",port:"",mount_point:"",
 now_playing_current_k:-1,now_playing_found:!1,now_playing_arr_lenght:0,now_playing_arr:["stats?sid=1","7.html","status-json.xsl","status.xsl"],history_current_k:0,history_arr:["played.html"],the_artist_id:"",the_wikidata_id:"",musicbrainz_setTimeout:"",no_artist_image_setTimeout:"",the_artist_id_history_arr:[""],the_wikidata_id_history_arr:[""],musicbrainzHistory_setTimeout_arr:[""],wiki_photo_path:a.noImageAvailable,zerx:"523532",html5_audio_tag:"",audioID:"hero_audio_tag_id_"+d};a.azuracast_get_image&&
 ""!=a.azuracast_api_nowplaying_url&&(a.grabLastFmPhoto=!1);""!=a.mscp_pro_api_url&&(a.grabLastFmPhoto=!1);a.iceCastFirst&&(c.now_playing_current_k=1,c.isHistoryGenerated=!0);a.preserveOriginalUpperLowerCase||(r.css({"text-transform":"uppercase"}),A.css({"text-transform":"capitalize"}));a.sticky||(a.startMinified=!1);30>a.nowPlayingInterval&&(a.nowPlayingInterval=44);a.showOnlyPlayButton&&(a.startMinified=!1,a.showFacebookBut=!1,a.showVolume=!1,a.showTwitterBut=!1,a.showRadioStation=!1,a.showTitle=
 !1,a.showHistoryBut=!1,a.showHistory=!1,a.playerWidth=l.width()+2*c.playHorizontalPadding,a.historyPadding=0);a.origWidth=a.playerWidth;c.temp_showHistoryBut=a.showHistoryBut;c.now_playing_arr_lenght=Object.keys(c.now_playing_arr).length;c.html5_audio_tag=u('<audio id="'+c.audioID+'" preload="metadata"></audio>');f.append(c.html5_audio_tag);-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&
 (a.autoPlay=!1),-1<navigator.userAgent.indexOf("Firefox")&&(a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));c.isFlashNeeded=fa(c);-1!=D&&(c.isFlashNeeded=!0);c.isFlashNeeded=!1;a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v3.2",status:!0,cookie:!0,xfbml:!0})},function(C,F,H){var M=C.getElementsByTagName(F)[0];C.getElementById(H)||(C=C.createElement(F),
 C.id=H,C.src="//connect.facebook.com/en_US/sdk.js",M.parentNode.insertBefore(C,M))}(document,"script","facebook-jssdk"),y.on("click",function(){FB.ui({method:"share_open_graph",action_type:"og.likes",action_properties:JSON.stringify({object:{"og:url":document.URL,"og:title":a.facebookShareTitle,"og:description":a.facebookShareDescription,"og:image":a.facebookShareImage}})},function(C){})}));if(a.showTwitterBut)p.on("click",function(){window.open("https://twitter.com/intent/tweet?url="+document.URL+
 "&text="+a.radio_name,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});U("block",c,a,f,I,g,G,E,l,A,x,r,e,b,n,z,h,v,B,k,q,w,t,m,p,y);c.audioPlayerHeight=n.height()+v.height()+k.height();a.showOnlyPlayButton&&(c.audioPlayerHeight=l.height()+2*c.playVerticalPadding);f.height(c.audioPlayerHeight);if(a.startMinified||a.showOnlyPlayButton)c.historyInitialHeight=0;c.wrapperHeight=c.audioPlayerHeight+c.historyInitialHeight+a.historyTopPos;a.showHistory&&a.showHistoryOnInit||
 (c.wrapperHeight=c.audioPlayerHeight);z.css({border:a.playerBorderSize+"px solid "+a.playerBorderColor,width:f.width()+"px",height:c.wrapperHeight+"px"});a.centerPlayer&&z.css({margin:"0 auto"});var g=u(".thumbsHolderWrapper",f),E=u(".historyPadding",f),G=u(".thumbsHolderVisibleWrapper",f),I=u(".thumbsHolder",f);c.audio6_html5_sliderVertical=u(".slider-vertical",f);E.css({padding:a.historyPadding+"px"});G.append('<div class="readingData">'+a.translateReadingData+"</div>");h.width(a.playerWidth-2*
 a.historyPadding);h.html(a.historyTranslate);h.css({color:a.historyTitleColor});a.showHistory||g.css({opacity:0});a.showHistoryOnInit||g.css({opacity:0,"margin-top":"-20px"});g.css({width:f.width()+"px",top:c.audioPlayerHeight+a.historyTopPos+"px",left:"0px",background:a.historyBgColor});G.width(f.width());a.sticky&&(z.addClass("audio6_html5_sticky_div"),q.on("click",function(){var C=500;if(c.isMinified){c.isMinified=!1;q.removeClass("AudioOpenBut");var F="block";c.temp_showHistoryBut=a.showHistoryBut;
 c.audioPlayerHeight=parseInt(a.playerWidth/a.origWidth*a.imageHeight,10)+v.height()+k.height();var H=0>g.css("margin-top").substring(0,g.css("margin-top").length-2)?c.audioPlayerHeight:c.audioPlayerHeight+g.height()+a.historyTopPos}else c.isMinified=!0,q.addClass("AudioOpenBut"),F="none",c.audioPlayerHeight=v.height()+k.height(),H=c.audioPlayerHeight,c.temp_showHistoryBut=!1;U(F,c,a,f,I,g,G,E,l,A,x,r,e,b,n,z,h,v,B,k,q,w,t,m,p,y);n.css({display:F});a.startMinified?(C=0,a.startMinified=!1):C=500;g.css({display:F,
 top:c.audioPlayerHeight+a.historyTopPos+"px"});c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({display:F,top:c.audioPlayerHeight+a.historyTopPos+2*a.historyPadding+2+h.height()+"px"});z.animate({height:H},C,"easeOutQuad",function(){})}));t.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(C,F){a.initialVolume=F.value;c.isFlashNeeded?c.myFlashObject.myAS3function(N(c,a,I,f),a.initialVolume):document.getElementById(c.audioID).volume=
 F.value},stop:function(C,F){}});document.getElementById(c.audioID).volume=a.initialVolume;t.css({background:a.volumeOffColor});u(".ui-slider-range",t).css({background:a.volumeOnColor});l.on("click",function(){var C=c.isFlashNeeded?!l.hasClass("AudioPause"):document.getElementById(c.audioID).paused;ea();0==C?(c.isFlashNeeded?c.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(c.audioID).pause(),l.removeClass("AudioPause")):(c.isFlashNeeded?c.myFlashObject.myAS3function("_play_radio_stream_",
 a.initialVolume):(document.getElementById(c.audioID).src=N(c,a,I,f),document.getElementById(c.audioID).load(),document.getElementById(c.audioID).play()),l.addClass("AudioPause"))});w.on("click",function(){if(0>g.css("margin-top").substring(0,g.css("margin-top").length-2)){var C=1;var F="block";var H="0px";var M=c.audioPlayerHeight+g.height()+a.historyTopPos;g.css({display:F});c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({opacity:1,display:"block"})}else C=0,F="none",
 H="-20px",c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),M=c.audioPlayerHeight;g.css({"z-index":-1});g.animate({opacity:C,"margin-top":H},500,"easeOutQuad",function(){g.css({display:F,"z-index":"auto"})});z.animate({height:M},500,"easeOutQuad",function(){})});m.on("click",function(){document.getElementById(c.audioID).muted?(document.getElementById(c.audioID).muted=!1,m.removeClass("VolumeButtonMuted"),c.isFlashNeeded&&(a.initialVolume=c.prevVolumeVal,
 c.myFlashObject.myAS3function(N(c,a,I,f),a.initialVolume))):(document.getElementById(c.audioID).muted=!0,m.addClass("VolumeButtonMuted"),c.isFlashNeeded&&(c.prevVolumeVal=a.initialVolume,a.initialVolume=0,c.myFlashObject.myAS3function(N(c,a,I,f),a.initialVolume)))});g.swipe({swipeStatus:function(C,F,H,M,ia,ja){"up"!=H&&"down"!=H||0==M||(C=c.audio6_html5_sliderVertical.slider("value"),C="up"==H?C-1.5:C+1.5,c.audio6_html5_sliderVertical.slider("value",C),u("html, body").off("touchstart touchmove").on("touchstart touchmove",
 function(ha){ha.preventDefault()}),Q(C,c,a,I))},threshold:100,maxTimeThreshold:500,fingers:"all",allowPageScroll:"none",preventDefaultEvents:!1});c.isFlashNeeded&&(c.rndNum=parseInt(998999*Math.random()+1E3),f.append("<div id='swfHolder"+c.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){c.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+a.radio_stream+"&autoPlay="+a.autoPlay+"&initialVolume="+a.initialVolume},"swfHolder"+
 c.rndNum)}),a.autoPlay&&l.addClass("AudioPause"));da(c,a,I,f,l,A,x,r,e,b,n,G,g,E,z,h,q);-1==K.indexOf("ipad")&&-1==K.indexOf("iphone")&&-1==K.indexOf("ipod")&&-1==K.indexOf("webos")||l.removeClass("AudioPause");var ba=function(){""==c.origParentFloat&&(c.origParentFloat=f.parent().css("float"),c.origParentPaddingTop=f.parent().css("padding-top"),c.origParentPaddingRight=f.parent().css("padding-right"),c.origParentPaddingBottom=f.parent().css("padding-bottom"),c.origParentPaddingLeft=f.parent().css("padding-left"));
 a.playerWidth!=a.origWidth||a.playerWidth>u(window).width()?f.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):f.parent().css({"float":c.origParentFloat,"padding-top":c.origParentPaddingTop,"padding-right":c.origParentPaddingRight,"padding-bottom":c.origParentPaddingBottom,"padding-left":c.origParentPaddingLeft});var C=f.parent().parent().width();if(f.width()!=C){a.playerWidth=a.origWidth>C?C:a.origWidth;if(f.width()!=a.playerWidth){U("block",c,
 a,f,I,g,G,E,l,A,x,r,e,b,n,z,h,v,B,k,q,w,t,m,p,y);c.audioPlayerHeight=n.height()+v.height()+k.height();c.isMinified&&(c.audioPlayerHeight=v.height()+k.height());f.height(c.audioPlayerHeight);c.wrapperHeight=c.audioPlayerHeight+g.height()+a.historyTopPos;if(!a.showHistory||!a.showHistoryOnInit||c.isMinified||0>g.css("margin-top").substring(0,g.css("margin-top").length-2))c.wrapperHeight=c.audioPlayerHeight;z.css({width:f.width()+"px",height:c.wrapperHeight+"px"});h.width(a.playerWidth-2*a.historyPadding);
 g.css({width:f.width()+"px",top:c.audioPlayerHeight+a.historyTopPos+"px"});G.width(f.width());O(c,a,f,I,g,G,E,l,A,x,r,e,b,n,z,h)}a.playerWidth<u(window).width()&&f.parent().css({"float":c.origParentFloat,"padding-top":c.origParentPaddingTop,"padding-right":c.origParentPaddingRight,"padding-bottom":c.origParentPaddingBottom,"padding-left":c.origParentPaddingLeft})}},V=!1;u(window).on("resize",function(){var C=!0;-1!=D&&9==D&&0==c.windowWidth&&(C=!1);c.windowWidth==u(window).width()?(C=!1,a.windowCurOrientation!=
 window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,C=!0)):c.windowWidth=u(window).width();a.responsive&&C&&(!1!==V&&clearTimeout(V),V=setTimeout(function(){ba()},300))});a.responsive&&ba()})};u.fn.audio6_html5.defaults={radio_stream:"http://194.232.200.150:80/;",radio_name:"Idobi Anthm",url_custom_metdata_file:"",metadata_file_type:"",playerWidth:335,imageHeight:335,skin:"whiteControllers",initialVolume:1,autoPlay:!0,loop:!0,playerBg:"#000000",
 volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",songTitleColor:"#ffffff",authorTitleColor:"#ffffff",lineSeparatorColor:"#636363",radioStationColor:"#ffffff",frameBehindTextColor:"#000000",frameBehindButtonsColor:"#454545",playerBorderSize:0,playerBorderColor:"#000000",sticky:!1,startMinified:!1,showOnlyPlayButton:!1,centerPlayer:!1,iceCastFirst:!1,showFacebookBut:!0,facebookAppID:"",facebookShareTitle:"HTML5 Radio Player With History - Shoutcast and Icecast",facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",
 facebookShareImage:"",showVolume:!0,showTwitterBut:!0,showRadioStation:!0,showTitle:!0,showHistoryBut:!0,showHistory:!0,showHistoryOnInit:!0,translateReadingData:"reading history...",historyTranslate:"HISTORY - latest played songs",historyTitleColor:"#858585",historyTopPos:0,historyBgColor:"#ebebeb",historyRecordBgColor:"transparent",historyRecordBottomBorderColor:"transparent",historyRecordSongColor:"#000000",historyRecordSongBottomBorderColor:"#d0d0d0",historyRecordAuthorColor:"#6d6d6d",numberOfThumbsPerScreen:3,
 historyPadding:16,preserveOriginalUpperLowerCase:!1,responsive:!0,historyRecordTitleLimit:25,historyRecordAuthorLimit:36,nowPlayingInterval:35,grabLastFmPhoto:!0,optional_images_path:"",azuracast_api_nowplaying_url:"",azuracast_get_image:!1,mscp_pro_api_url:"",pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",lastFMApiKey:"",lastFMSecret:"",origWidth:0,isSliderInitialized:!1,isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
